ci: update install nix action
Looks like the version of nix brought in by action v22 is too old at this point.

The build check was failing with

        error: unsupported tarball input attribute 'lastModified'

The action was installing 2.15 previously which is quite old.